FROM python:3.11-slim

WORKDIR /app

# Копируем зависимости и устанавливаем
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код, данные и модель
COPY app/ ./app/
COPY data/ ./data/
COPY models/ ./models/
COPY .env ./

EXPOSE 8000

# Запуск FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]